// Auto-generated by LibreLane
module mini_light_up_game(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input btn,
  output[6:0] seg0,
  output[6:0] seg1,
  output[6:0] seg2,
  output[6:0] seg3
);
endmodule
